backend:
  name: github
  repo: legalinsajaid/legalinsaja.id  # ganti sesuai repo kamu
  branch: master

media_folder: "images"       # tempat upload gambar
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Konten", name: "body", widget: "markdown" }